image: docker:stable
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - build
  - push
build:
  stage: build
  services:
   - name: docker:dind
     command: ["--insecure-registry=registry.hub.docker.com"]
  script:
    - docker build -t zeemyself/rn-android .
  artifacts:
    paths:
      - /var/lib/docker
push:
  stage: push
  before_script:
    - docker login -u zeemyself -p $DOCKER_TOKEN registry.hub.docker.com
  script:
    - docker push registry.hub.docker.com/zeemyself/rn-android
  when: manual

