image: docker:stable
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - build
build:
  stage: build
  services:
   - name: docker:dind
  script:
    - docker build -t registry.wndv.co/rn-android .
    - docker push registry.wndv.co/rn-android

