image: docker:stable
stages:
  - build
  - push
build:
  stage: build
  services:
   - docker:dind
  script:
    - docker build -t zeemyself/rn-android .
push:
  stage: push
  before_script:
    - docker login -u zeemyself -p $DOCKER_TOKEN
  script:
    - docker push zeemyself/rn-android
  when: manual

