image: docker:stable
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - build
  - push
build:
  stage: build
  services:
   - docker:dind
     command: [ "--insecure-registry=registry.hub.docker.com" ]
  script:
    - docker build -t zeemyself/rn-android .
push:
  stage: push
  before_script:
    - docker login -u zeemyself -p $DOCKER_TOKEN
  script:
    - docker push zeemyself/rn-android
  when: manual

